name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "locales/**"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          MONGO_CONNECTION: ${{secrets.MONGO_CONNECTION}}
          ERROR_WEBHOOK: $${{secrets.ERROR_WEBHOOK}}
          NODE_ENV: production

      - name: Cleanup Unused Images
        run: docker image prune -f

